SistemaVendas/Controllers/RelatorioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SistemaVendas.Models;

namespace SistemaVendas.Controllers
{
    public class RelatorioController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult RelatorioVendas()
        {
            List<VendaModel> listaVendas = new VendaModel().ListaVendas(null, null, false);
            ViewBag.listaVendas = listaVendas;

            return View();
        }

        [HttpPost]
        public IActionResult RelatorioVendas(RelatorioModel relatorio)
        {
            List<VendaModel> listaVendas = new VendaModel().ListaVendas(relatorio.DataInicio, relatorio.DataFim, false);
            ViewBag.listaVendas = listaVendas;

            return View();
        }

        [HttpGet]
        public IActionResult Grafico()
        {
            List<GraficoProdutos> lista = new GraficoProdutos().RetornarGrafico();
            string valores = string.Empty;
            string labels = string.Empty;
            string cores = string.Empty;

            var random = new Random();

            //Percorre a lista de itens para compor o gráfico.
            for (int i = 0; i < lista.Count; i++)
            {
                valores += lista[i].QtdVendido.ToString() + ",";
                labels += "'" + lista[i].DescricaoProduto.ToString() + "',";
                //Escolher aleatoriamente as cores para compor as partes do grafico tipo torta
                cores += "'" + string.Format("#{0:X6}", random.Next(0x1000000)) +"',";
            }

            ViewBag.Valores = valores;
            ViewBag.Labels = labels;
            ViewBag.Cores = cores;

            return View();
        }
    }
}

SistemaVendas/Views/Relatorio/Comissao.cshtml
<h2>Comissao</h2>

SistemaVendas/Views/Relatorio/Grafico.cshtml
<h2>Grafico de vendas por produtos</h2>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>

<div id="canvas-holder" style="width:40%">
    <canvas id="chart-area"></canvas>
</div>

<script>
    var randomScalingFactor = function () {
        return Math.round(Math.random() * 100);
    };

    var config = {
        type: 'pie',
        data: {
            datasets: [{
                data: [@Html.Raw(ViewBag.Valores)],
                backgroundColor: [@Html.Raw(ViewBag.Cores)],
                label: 'Dataset 1'
            }],
            labels: [@Html.Raw(ViewBag.Labels)]
        },
        options: {
            responsive: true
        }
    };

    window.onload = function () {
        var ctx = document.getElementById('chart-area').getContext('2d');
        window.myPie = new Chart(ctx, config);
    };
</script>

SistemaVendas/Views/Relatorio/Index.cshtml
<h2>Relatórios do sistema</h2>

<button class="btn btn-block btn-primary" type="button" onclick="irParaRelatorio('RelatorioVendas')">Vendas por período</button>
<button class="btn btn-block btn-block" type="button" onclick="irParaRelatorio('Grafico')">Gráfico de vendas</button>
<button class="btn btn-block btn-default" type="button" onclick="irParaRelatorio('')">Comissão de vendedores</button>

<script>

    function irParaRelatorio(relatorio) {
        window.location.href = '../Relatorio/' + relatorio;
    }

</script>

SistemaVendas/Views/Relatorio/RelatorioVendas.cshtml
@model RelatorioModel

<h2>Vendas por período</h2>

<form asp-controller="Relatorio" asp-action="RelatorioVendas">

    <div class="form-group">
        <label>Informe o período:</label>
        <br />
        <input asp-for="DataInicio" type="date" class="form-control" id="dataInicio">
        <input asp-for="DataFim" type="date" class="form-control" value="Data final" id="dataFim">
    </div>

    <button type="submit" class="btn btn-success" onclick="mostrarTabela()">Pesquisar</button>

    <table class="table table-bordered" id="tabelaVendas">
        <thead>
            <tr>
                <th>ID</th>
                <th>Data</th>
                <th>Total</th>
                <th>Vendedor</th>
                <th>Cliente</th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var item in (List<VendaModel>)ViewBag.listaVendas)
                {
                    <tr>
                        <td>@item.ID</td>
                        <td>@item.data</td>
                        <td>@item.total</td>
                        <td>@item.vendedor</td>
                        <td>@item.cliente</td>
                    </tr>
                }
            }
        </tbody>
    </table>

</form>

<script>

    $('#dataInicio').val('');
    $('#dataFim').val('');

</script>